### ISSUE TITLE
Enemies are able to be stunned upon being hit by Ruby

### ISSUE THREAD

**Issue by Jolov-MTU** [HuskyGameDev/2020s-team12#11]
- When enemies are hit by Ruby's bullets, they stop moving for a brief period
- The stun time should be able to be adjusted per enemy (public var)

**Comment by mcgonzale** [comment]
c05fdf8b821205bf2055ec5bf8c30de2715bd50b
added enemy stun, can be changed with variable in health script (Knock Timer)
