### ISSUE TITLE
Power-ups!

### ISSUE THREAD

**Issue by Jolov-MTU** [HuskyGameDev/2020s-team12#17]
- Create and implement a few basic power ups that can be picked up off of the ground (they do not have to be dropped by enemies yet).
- Each power-up should have its own sprite that represents the boost that it gives Ruby.
- Duration, power, and other relevant variables should all be editable in the scene.

**Comment by mcgonzale** [comment]
Added rapid fire implementation with c867b5ceab01b2a2f3212daa443e4748d0d7447b

**Comment by Jolov-MTU** [comment]
UPDATE:
- Each individual powerup should have its own stats. The script that buffs Ruby should most likely not be attached to the Ruby gameobject

**Comment by mcgonzale** [comment]
Refactored rapid fire, added health pickup with 86c6d3a5fd83ccf80828672f0b0b84a45d73f78d

**Comment by mcgonzale** [comment]
Currently working on spread shot; we can alter how many shots are fired at a time (typically 3 seems good). Made a bit of progress today, but still not my desired result.

*DAY AFTER EDIT: The powerup now shoots 3 shots! They all have the same angle, and have weird starting positions relative to the player.

**Comment by mcgonzale** [comment]
Deadline by March 15, 2020 (Sunday)

Extend Deadline, March 22

**Comment by mcgonzale** [comment]
Added sprites.
Multi shot is still not working as I would like. I would like some help fixing it. For now, it works fine.
022140664444f5f95b604d4dc323ea815e96d6b7

**Comment by mcgonzale** [comment]
Merged to master
29fbfe8df2ec677e44ac93da6c5b562eca634c0e
