### ISSUE TITLE
Decide on Ambient Sound

### ISSUE THREAD

**Issue by Jolov-MTU** [HuskyGameDev/2020s-team12#20]
- Describe the ambient noise and sound that should play during the game.
- Can be a list of individual sounds that play on random intervals.
- Ambient, creepy music that fits with our horror theme.
- Find examples from other games or find actual sound bytes online.
- Bring it up as a vote on slack to make sure everyone agrees.
- Send details and example to our sound design member.

**Comment by Wolfehh** [comment]
https://www.youtube.com/watch?v=Eu8tlx4fChs

Additionally: https://www.youtube.com/watch?v=ugNx8Tf3mok for dialogue scenes
https://www.youtube.com/watch?v=v4Ag9Sy1VUE Alternatively dialogue
https://www.youtube.com/watch?v=wtlWr8pPErE
https://www.youtube.com/watch?v=TaSDL5OaA5c
maybe music box is our go to bro
https://www.youtube.com/watch?v=qB5j6R7g_U4
music box resolution

**Comment by Wolfehh** [comment]
https://www.youtube.com/watch?v=v4Ag9Sy1VUE Alternatively dialogue

**Comment by Wolfehh** [comment]
https://www.youtube.com/watch?v=wtlWr8pPErE
maybe music box is our go to bro

**Comment by Wolfehh** [comment]
https://www.youtube.com/watch?v=qB5j6R7g_U4
music box resolution
