### ISSUE TITLE
Separate enemy collision from enemy hurtbox

### ISSUE THREAD

**Issue by Jolov-MTU** [HuskyGameDev/2020s-team12#25]
- Currently, the enemy collision box is the collision box also used to determine whether the enemy is hit by Ruby's projectile
- Separate the enemy's collision from its hurtbox so we can change how the enemy collides with obstacles without changing how it collides with Ruby's hearts.

**Comment by Wolfehh** [comment]
Using tile illusions instead of a separate hurtbox.
8f8255ec8cc09a00913cf789cb0a830804bd63c6
