### ISSUE TITLE
Ruby knocked down

### ISSUE THREAD

**Issue by Jolov-MTU** [HuskyGameDev/2020s-team12#30]
- Make a sprite for when ruby gets knocked back

**Comment by lilypadlilith** [comment]
Deadline: 3/12/20

**Comment by lilypadlilith** [comment]
I've decided to delay this until after the final Ruby sprites are implemented so I can make sprites that match. Feel free to mark me down for not saying something sooner.

**Comment by lilypadlilith** [comment]
New Deadline: 3/31/20

**Comment by Wolfehh** [comment]
Not implementing
