### ISSUE TITLE
Reticle

### ISSUE THREAD

**Issue by Wolfehh** [HuskyGameDev/2020s-team12#40]
- Write a script that changes the mouse pointer into a reticle and vice versa. 
- In the main menu, the pointer is like a normal mouse pointer but changes upon hovering a button
- Upon entering the game, the mouse pointer changes into a shooting reticle
For help making the script : https://docs.unity3d.com/ScriptReference/Cursor.SetCursor.html

**Comment by Jolov-MTU** [comment]
DEADLINE: 3/15/20

**Comment by Jolov-MTU** [comment]
on hold until we finish reticle sprites

**Comment by Jolov-MTU** [comment]
a6dfc234fe325fa498d58c3515e2c58c17b74151
