### ISSUE TITLE
Powerup Clarity

### ISSUE THREAD

**Issue by Jolov-MTU** [HuskyGameDev/2020s-team12#44]
- Add a hud element that shows up when Ruby is under the effects of a powerup.

**Comment by Wolfehh** [comment]
DEADLINE: 3/15/20

**Comment by mcgonzale** [comment]
Task is almost complete; waiting to commit because there is one small issue with the code. Bar displays time remaining in powerup, but I still have yet to add a sprite pop-up indicator of the powerup to the screen

**Comment by mcgonzale** [comment]
36c6f6f862b92ee0fe2b98ee5463c0583367c451
bar ticks down when powerup is in effect, indicating time remaining. I would like to add a sprite pop up soon to the HUD that shows the current active effect.

**Comment by mcgonzale** [comment]
Extend Deadline, March 22

**Comment by mcgonzale** [comment]
5b4e69088374fcf1e20b420108640aec87bed0c9
added sprite pop up to the HUD that shows the current active effect.

**Comment by mcgonzale** [comment]
Merged to Master
29fbfe8df2ec677e44ac93da6c5b562eca634c0e
