### ISSUE TITLE
Movement fix

### ISSUE THREAD

**Issue by mcgonzale** [HuskyGameDev/2020s-team12#5]
Our playable dot can move diagonally just fine if you press both keys at the same time, but if the lateral directional key is pressed first, and the longitudinal key pressed second (or vise versa), the dot doesn't properly move diagonally. I have been trying to remedy the problem with our current vector-based movement, but I propose we return to the movement code we had at our first meeting.

**Comment by Wolfehh** [comment]
We didn't change the movement code.

**Comment by mcgonzale** [comment]
Closed with 2ec27236c0eec1997dfc5ad2579f9b00b23b5aac

Changed sensitivity and gravity to 60. Sets input axes to 0 or 1 within a single frame

**Comment by Wolfehh** [comment]
I have no idea where u got gravity from, but we can discuss it on Thursday.
