### ISSUE TITLE
Final Ruby Sprites

### ISSUE THREAD

**Issue by lilypadlilith** [HuskyGameDev/2020s-team12#51]
Replace the placeholder character (the gray blob) with Ruby's final sprites

**Comment by lilypadlilith** [comment]
Deadline: 3/19/20

**Comment by lilypadlilith** [comment]
New Deadline: 3/30/20 🙇‍♀️🙇‍♀️🙇‍♀️

**Comment by Wolfehh** [comment]
f259ac0bbd2510673e502177f622f82b3592ff55
