### ISSUE TITLE
Enemy doesnt take damage

### ISSUE THREAD

**Issue by mcgonzale** [HuskyGameDev/2020s-team12#6]
Aaaag something that I did makes the enemy immune to Death! I will fix when I have freetime; my apologies.

**Comment by Wolfehh** [comment]
Why are you touching finished code? Also don't push broken code please.

**Comment by mcgonzale** [comment]
Nothing about our code can be or should be considered finished. And it was an honest mistake and I do not have time to fix it

**Comment by Wolfehh** [comment]
Okay then explain the entire issue with screenshots next time please. I would say the code is done for Sprint 1 usage.

**Comment by Jolov-MTU** [comment]
Resolved
