### ISSUE TITLE
Level 3 Mechanics (Enemy AI Improvements)

### ISSUE THREAD

**Issue by Jolov-MTU** [HuskyGameDev/2020s-team12#7]
- Enemy detection radius: Enemy does not move towards Ruby unless Ruby is within a set radius.

**Comment by Wolfehh** [comment]
Ethan, Jessie, Jolo - Detection Radius Done

**Comment by Wolfehh** [comment]
https://github.com/HuskyGameDev/2020s-team12/commit/77cf247c5b293206d901275e75207c5d69df186a
