### ISSUE TITLE
Shooter-type Enemy

### ISSUE THREAD

**Issue by Jolov-MTU** [HuskyGameDev/2020s-team12#8]
- Create a new enemy that shoots at Ruby instead of aiming to touch her.
- Movement: The enemy should either have a predetermined path or be stationary while it shoots at Ruby.
- Shooting: Enemy projectiles should be shot at Ruby's current location, and move slower in comparison to her movement and her bullets. (Maybe it moves so slowly that Ruby has to consciously avoid its path whilst kiting the chaser-type enemies).
- Less health than chaser-type enemies.
- Projectiles should do more damage on contact than chaser-type enemies. (tentative)

**Comment by Jolov-MTU** [comment]
DEADLINE: 3/15/20

**Comment by kajackso** [comment]
there is progress, but deadline was not met. Will be done by the end of sprint 3

**Comment by kajackso** [comment]
Shooting script is done, working on enemy implementation. The implementation is simple for the shooting script, but I'm looking into doing some extra stuff as well.
